/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:51
-- pg_trex::pg_trex_query
CREATE  FUNCTION "pg_trex_query"(
	"sql" TEXT /* &str */
) RETURNS TABLE (
	"result" TEXT  /* alloc::string::String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_trex_query_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:73
-- pg_trex::pg_trex_status
CREATE  FUNCTION "pg_trex_status"() RETURNS TABLE (
	"state" TEXT,  /* alloc::string::String */
	"active_queries" INT,  /* i32 */
	"catalog_entries" INT,  /* i32 */
	"gossip_addr" TEXT,  /* alloc::string::String */
	"flight_addr" TEXT,  /* alloc::string::String */
	"data_node" bool  /* bool */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_trex_status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:73
-- pg_trex::pg_trex_distributed_query
CREATE  FUNCTION "pg_trex_distributed_query"(
	"sql" TEXT /* &str */
) RETURNS TABLE (
	"result" TEXT  /* alloc::string::String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_trex_distributed_query_wrapper';
/* </end connected objects> */

