#!/bin/bash
set -e

# Combines a base Dockerfile with extension BEFORE/AFTER sections (split by an
# `### INCLUDE_BASE ###` marker) into a single generated Dockerfile.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/../../../.."

BASE_DOCKERFILE="Trex/trexsql/bao/Dockerfile"
EXTENSION_DOCKERFILE="Trex/trexsql/bao/Dockerfile.runtime"
OUTPUT_DOCKERFILE="Dockerfile"

echo "Generating combined Dockerfile..."

echo "# syntax=docker/dockerfile:1.4" > "$OUTPUT_DOCKERFILE"
echo "# AUTO-GENERATED - DO NOT EDIT MANUALLY" >> "$OUTPUT_DOCKERFILE"
echo "# Generated by build-docker.sh from $BASE_DOCKERFILE and $EXTENSION_DOCKERFILE" >> "$OUTPUT_DOCKERFILE"
echo "" >> "$OUTPUT_DOCKERFILE"

if [ -f "$EXTENSION_DOCKERFILE" ]; then
    if grep -q "### INCLUDE_BASE ###" "$EXTENSION_DOCKERFILE"; then
        echo "# ===== BEFORE section =====" >> "$OUTPUT_DOCKERFILE"
        sed -n '1,/### INCLUDE_BASE ###/p' "$EXTENSION_DOCKERFILE" | grep -v "### INCLUDE_BASE ###" | grep -v "^# Use the marker" >> "$OUTPUT_DOCKERFILE"
        echo "" >> "$OUTPUT_DOCKERFILE"
    fi
fi

echo "# ===== Base =====" >> "$OUTPUT_DOCKERFILE"
# Strip the base's syntax line and CMD, and rewrite $BASEPATH so paths resolve
# from the generated Dockerfile's location.
grep -v "^# syntax=" "$BASE_DOCKERFILE" | grep -v "^CMD " | sed 's|\$BASEPATH|Trex/trexsql/bao|g' | sed 's|ENV BASEPATH=.*|ENV BASEPATH=Trex/trexsql/bao|' >> "$OUTPUT_DOCKERFILE"
echo "" >> "$OUTPUT_DOCKERFILE"

if [ -f "$EXTENSION_DOCKERFILE" ]; then
    if grep -q "### INCLUDE_BASE ###" "$EXTENSION_DOCKERFILE"; then
        echo "# ===== AFTER section =====" >> "$OUTPUT_DOCKERFILE"
        sed -n '/### INCLUDE_BASE ###/,$p' "$EXTENSION_DOCKERFILE" | tail -n +2 >> "$OUTPUT_DOCKERFILE"
        echo "Combined: BEFORE + $BASE_DOCKERFILE + AFTER -> $OUTPUT_DOCKERFILE"
    else
        echo "Generated $OUTPUT_DOCKERFILE from $BASE_DOCKERFILE (extension file has no INCLUDE_BASE marker)"
    fi
else
    echo "Generated $OUTPUT_DOCKERFILE from $BASE_DOCKERFILE (no extension file found)"
fi

echo "Dockerfile generation complete."
echo ""
echo "To build the image, run:"
echo "  docker build -t trextest ."
