#!/bin/bash
set -e

# Script to combine Dockerfiles and generate the final Dockerfile
# Reads base Dockerfile from Trex/trexsql/bao/Dockerfile
# Reads extension from Dockerfile.runtime with BEFORE and AFTER sections
# Generates combined Dockerfile in services/trex/Dockerfile

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Navigate to services/trex directory (4 levels up from scripts/)
cd "$SCRIPT_DIR/../../../.."

BASE_DOCKERFILE="Trex/trexsql/bao/Dockerfile"
EXTENSION_DOCKERFILE="Trex/trexsql/bao/Dockerfile.runtime"
OUTPUT_DOCKERFILE="Dockerfile"

echo "Generating combined Dockerfile..."

# Start with syntax declaration
echo "# syntax=docker/dockerfile:1.4" > "$OUTPUT_DOCKERFILE"
echo "# AUTO-GENERATED - DO NOT EDIT MANUALLY" >> "$OUTPUT_DOCKERFILE"
echo "# Generated by build-docker.sh from $BASE_DOCKERFILE and $EXTENSION_DOCKERFILE" >> "$OUTPUT_DOCKERFILE"
echo "" >> "$OUTPUT_DOCKERFILE"

# If extension exists, add BEFORE section
if [ -f "$EXTENSION_DOCKERFILE" ]; then
    # Extract everything before ### INCLUDE_BASE ### marker
    if grep -q "### INCLUDE_BASE ###" "$EXTENSION_DOCKERFILE"; then
        echo "# ===== BEFORE section =====" >> "$OUTPUT_DOCKERFILE"
        sed -n '1,/### INCLUDE_BASE ###/p' "$EXTENSION_DOCKERFILE" | grep -v "### INCLUDE_BASE ###" | grep -v "^# Use the marker" >> "$OUTPUT_DOCKERFILE"
        echo "" >> "$OUTPUT_DOCKERFILE"
    fi
fi

# Add base Dockerfile content, adjusting paths
echo "# ===== Base =====" >> "$OUTPUT_DOCKERFILE"
# Remove syntax line, replace $BASEPATH with Trex/trexsql/bao, and remove CMD line from base
grep -v "^# syntax=" "$BASE_DOCKERFILE" | grep -v "^CMD " | sed 's|\$BASEPATH|Trex/trexsql/bao|g' | sed 's|ENV BASEPATH=.*|ENV BASEPATH=Trex/trexsql/bao|' >> "$OUTPUT_DOCKERFILE"
echo "" >> "$OUTPUT_DOCKERFILE"

# If extension exists, add AFTER section
if [ -f "$EXTENSION_DOCKERFILE" ]; then
    if grep -q "### INCLUDE_BASE ###" "$EXTENSION_DOCKERFILE"; then
        echo "# ===== AFTER section =====" >> "$OUTPUT_DOCKERFILE"
        sed -n '/### INCLUDE_BASE ###/,$p' "$EXTENSION_DOCKERFILE" | tail -n +2 >> "$OUTPUT_DOCKERFILE"
        echo "✓ Combined: BEFORE + $BASE_DOCKERFILE + AFTER -> $OUTPUT_DOCKERFILE"
    else
        echo "✓ Generated $OUTPUT_DOCKERFILE from $BASE_DOCKERFILE (extension file has no INCLUDE_BASE marker)"
    fi
else
    echo "✓ Generated $OUTPUT_DOCKERFILE from $BASE_DOCKERFILE (no extension file found)"
fi

echo "✓ Dockerfile generation complete!"
echo ""
echo "To build the image, run:"
echo "  docker build -t trextest ."
